apiVersion: apps/v1
kind: Deployment
metadata:
  name: entertainment-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: entertainment-app
  template:
    metadata:
      labels:
        app: entertainment-app
    spec:
      containers:
      - name: entertainment-container
        image: entertainment-react-app
        imagePullPolicy: Never
        ports:
        - containerPort: 80